databases:
  - name: FakeFriends
    databaseName: FakeFriends
    user: FakeFriends

services:
  - type: web
    name: FakeFriends
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: FakeFriends
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
