databases:
  - name: fakefriends-database
    plan: free

services:
  - type: web
    name: fakefriends
    plan: free
    region: frankfurt
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fakefriends-database
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      fromService:
        type: redis
        name: fakefriends-redis
        property: connectionString


- type: redis
    name: fakefriends-redis
    ipAllowList: # required
      - source: 0.0.0.0/0
        description: everywhere
    plan: free # optional (defaults to starter instance type)
