apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fakefriends.fullname" . }}-db-secret
  labels:
    {{- include "fakefriends.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.db.DATABASE_PASSWORD | b64enc | quote }}
