development:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', "redis://#{Rails.configuration.redis_host}:#{Rails.configuration.redis_port}/1") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', "redis://#{Rails.configuration.redis_host}:#{Rails.configuration.redis_port}/1") %>
  channel_prefix: rails_authentication_production
