development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test
# Following code not necessary for render.com
# production:
#   adapter: redis
#   url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
#   channel_prefix: rails_authentication_production
