development:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_API_KEY"] %>
  secure: true
# Following code not necessary for render.com
# production:
#   cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
#   api_key: <%= ENV["CLOUDINARY_API_KEY"] %>
#   api_secret: <%= ENV["CLOUDINARY_API_KEY"] %>
#   secure: true
