name: Helm Chart Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Application version (for manual triggers)"
        required: true
        default: "1.0.0"

jobs:
  release-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "app_version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            APP_VERSION=${GITHUB_REF#refs/tags/v}
            echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT
          fi

      - name: Update image tag in values.yaml
        run: |
          # Only update the image tag in values.yaml
          sed -i "s/tag:.*/tag: \"${{ steps.version.outputs.app_version }}\"/" k8s/helm/fakefriends/values.yaml

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package and push Helm chart to OCI registry
        run: |
          helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          helm package k8s/helm/fakefriends/
          CHART_VERSION=$(grep 'version:' k8s/helm/fakefriends/Chart.yaml | awk '{print $2}')
          helm push fakefriends-${CHART_VERSION}.tgz oci://registry-1.docker.io/${{ secrets.DOCKERHUB_USERNAME }}/charts
